import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {PriceStore,dayKey,dayKeysBetween} from '../src/store.mjs';import {encode,decode,mapQuote,mapInformationQuotes} from '../src/protocol.mjs';import {aggregateCandles} from '../src/candles.mjs';import {isEmail,validateMailbox} from '../src/mail.mjs';
test('binary wire roundtrip preserves prices and source time',()=>{const message={msgid:0,seq:-4,response:[{quotation:[{code:'JZJ_au_PB',quoteTime:1788927240000,rt:{last:941.45}}]}]};const result=decode(encode(message));assert.equal(result.response[0].quotation[0].rt.last,941.45);assert.equal(result.response[0].quotation[0].quoteTime,'1788927240000');assert.equal(result.seq,-4)});
test('metadata determines side, precision and rejects invalid prices',()=>{const map=new Map([['JZJ_ag_PB',{group:'JZJ_ag',bsflag:'B',prcs:3}]]);const item=mapQuote({code:'JZJ_ag_PB',open:14.8,high:15,low:14.7,preClose:14.75,rt:{last:14.853,updown:.103,updownRate:.7}},map);assert.deepEqual(item,{code:'JZJ_ag',side:'bid',price:14.853,precision:3,sourceTime:null,open:14.8,high:15,low:14.7,preClose:14.75,updown:.103,updownRate:.7});for(const last of [NaN,Infinity,0,-1,null,'14'])assert.equal(mapQuote({code:'JZJ_ag_PB',rt:{last}},map),null);assert.equal(mapQuote({code:'UNKNOWN',rt:{last:3}},map),null)});
test('SQLite persists pending writes and keeps only today official product data',async()=>{const folder=fs.mkdtempSync(path.join(os.tmpdir(),'silver-monitor-test-'));let store;try{store=await PriceStore.open(folder);const now=Date.now();const item={id:randomUUID(),code:'JZJ_ag',side:'bid',price:14.941,precision:3,sourceTime:String(now-1000),time:now,session:'a'};assert.equal(store.append(item),true);store.flush();store.append({...item,id:randomUUID(),price:14.942,time:now+1});store.db.close();store.db=null;store=await PriceStore.open(folder);assert.equal(store.history('JZJ_ag','bid',1,now+10).length,2);store.close();store=await PriceStore.open(folder);assert.equal(store.history('JZJ_ag','bid',1,now+10).length,2);assert.equal(store.history("' OR 1=1 --",'bid',1,now+10).length,0);assert.equal(store.history('JZJ_ag','ask',1,now+10).length,0);const yesterday=new Date(`${dayKey(now)}T00:00:00+08:00`).getTime()-1000;assert.equal(store.append({...item,id:randomUUID(),time:yesterday,price:14.94}),false);assert.equal(store.append({...item,id:randomUUID(),code:'JZJ_au',time:now+2}),true);assert.equal(store.history('JZJ_au','bid',1,now+10).length,1);store.append({...item,id:randomUUID(),time:now+2,side:'ask',price:15.045});assert.equal(store.history('JZJ_ag','bid',24,now+10).length,2);assert.equal(dayKey(Date.UTC(2026,8,8,16,0,0)),'2026-09-09');}finally{store?.close();fs.rmSync(folder,{recursive:true,force:true})}});
test('candles aggregate open high low close and activity',()=>{const base=Date.UTC(2026,8,8,1);const list=aggregateCandles([{time:base,price:14.8,precision:3,session:'a'},{time:base+20000,price:14.9,precision:3,session:'a'},{time:base+70000,price:14.7,precision:3,session:'a'}],1);assert.equal(list.length,2);assert.deepEqual({...list[0],time:0},{time:0,open:14.8,high:14.9,low:14.8,close:14.9,count:2,precision:3,session:'a'});assert.equal(list[1].close,14.7)});

test('official information quotes retain real tick times for second candles',()=>{const points=mapInformationQuotes({response:[{quotation:[{code:'JZJ_ag_PS',quoteTime:'1789173930124',rt:{last:14.55}},{code:'OTHER',quoteTime:'1789173931124',rt:{last:99}}]}]},'JZJ_ag_PS');assert.equal(points.length,1);assert.equal(points[0].time,1789173930124);assert.equal(points[0].price,14.55)});
test('email validation and multi-day enumeration are strict',()=>{assert.equal(isEmail('a@example.com'),true);assert.equal(isEmail('bad'),false);assert.throws(()=>validateMailbox({host:'smtp.example.com',port:465,user:'a@example.com',password:'x',to:[]}));assert.equal(validateMailbox({host:'smtp.example.com',port:587,user:'a@example.com',password:'x',to:['b@example.com']}),true);assert.equal(dayKeysBetween(Date.parse('2026-09-01T12:00:00+08:00'),Date.parse('2026-09-04T12:00:00+08:00')).length,4)});


