import { EventEmitter } from 'node:events';
import WebSocket from 'ws';
import { Blowfish } from 'egoroof-blowfish';
import { randomUUID } from 'node:crypto';
import { METALS,OFFICIAL_PERIODS,encode,decode,mapQuote,mapHistoricalQuotes,mapInformationQuotes } from './protocol.mjs';
import { aggregateCandles } from './candles.mjs';
export class Feed extends EventEmitter {
 constructor(socketFactory=(url,options)=>new WebSocket(url,options)){super();this.socketFactory=socketFactory;this.lastSource=new Map();this.stopped=true;this.metadata=new Map();this.pending=new Map();this.attempt=0;this.lastMessage=0;this.socket=null;this.retry=null;this.seq=0;this.lastPrices=new Map();this.state={status:'stopped',message:'尚未开始',market:'市场状态待确认',lastMessage:0,session:null};this.quotes=METALS.map(([code,name])=>({code,name,bid:null,ask:null,bidTime:0,askTime:0,precision:2,available:false}));}
 publish(status,message){Object.assign(this.state,{status,message,lastMessage:this.lastMessage});this.emit('status',this.snapshot())}
 snapshot(){return {...this.state,lastMessage:this.lastMessage,quotes:this.quotes.map(q=>({...q}))}}
 start(){if(!this.stopped)return;this.stopped=false;this.connect()}
 send(msgid,request={},json){if(this.socket?.readyState!==WebSocket.OPEN)throw Error('行情连接尚未就绪');const current=this.seq++;this.socket.send(encode({msgid,seq:current,request,...(json?{jsonReq:JSON.stringify(json)}:{})}));return current}
 request(msgid,request={},json,timeout=15000){return new Promise((resolve,reject)=>{let current;try{current=this.send(msgid,request,json)}catch(error){reject(error);return}const timer=setTimeout(()=>{this.pending.delete(current);reject(Error('融通金历史行情读取超时'))},timeout);this.pending.set(current,{resolve,reject,timer})})}
 connect(){if(this.stopped)return;clearTimeout(this.retry);this.seq=0;this.lastMessage=0;this.metadata.clear();this.lastPrices.clear();this.lastSource.clear();this.state.session=randomUUID();this.quotes.forEach(q=>{q.available=false;q.bidCurrent=false;q.askCurrent=false});this.publish('connecting','正在连接融通金');
  const ws=this.socket=this.socketFactory('wss://rtjwbqt.ytj9999.com:8443/gateway',{origin:'https://i.jzj9999.com',handshakeTimeout:15000,maxPayload:8*1024*1024});
  let authenticated=false,ready=false;const started=Date.now();
  const timer=setInterval(()=>{if(ws!==this.socket)return;if(!authenticated&&Date.now()-started>20000){ws.terminate();return}if(authenticated){if(Date.now()-this.lastMessage>50000){ws.terminate();return}try{this.send(16)}catch{}if(!ready&&Date.now()-started>30000)ws.terminate()}},10000);
  ws.on('open',()=>{const bf=new Blowfish('tdc5%y4yaU@xFi',Blowfish.MODE.CBC,Blowfish.PADDING.PKCS5);bf.setIv('5X4f$^hp');this.send(32,{auth:{apptype:'rtj',token:bf.encode(`plaintractrtj${Date.now()}`)}})});
  ws.on('message',bytes=>{if(ws!==this.socket)return;try{const msg=decode(bytes);this.lastMessage=Date.now();const pending=this.pending.get(Math.abs(Number(msg.seq)));if(pending){clearTimeout(pending.timer);this.pending.delete(Math.abs(Number(msg.seq)));if(msg.errMsg||(msg.response||[]).some(r=>r.errCode))pending.reject(Error(msg.errMsg||(msg.response||[]).find(r=>r.errCode)?.msg||'融通金历史行情返回错误'));else pending.resolve(msg);if(msg.msgid===20)return}if(msg.errMsg||(msg.response||[]).some(r=>r.errCode)){this.publish('error','行情服务返回错误，稍后重连');ws.terminate();return}
   if(msg.msgid===32){if(!msg.response?.some(r=>r.auth))throw Error('auth');authenticated=true;this.send(66,{},{});this.send(28,{codes:['RTJ']})}
   if(msg.msgid===66&&msg.jsonResp){const base=JSON.parse(msg.jsonResp);if(!Array.isArray(base.codes))throw Error('metadata');for(const m of base.codes)this.metadata.set(m.code,m);const tradable=base.codes.filter(m=>m.group&&['B','S'].includes(m.bsflag));const codes=tradable.map(m=>m.code);if(!codes.length)throw Error('codes');const groups=new Map();for(const m of tradable){if(!groups.has(m.group))groups.set(m.group,{code:m.group,name:m.name||m.group,bid:null,ask:null,bidTime:0,askTime:0,precision:Number.isInteger(m.prcs)?m.prcs:3,available:false});}this.quotes=[...groups.values()];this.send(18,{codes,freq:[0]});ready=true;this.attempt=0;this.publish('connected','行情已连接');this.emit('metadata',tradable)}
   for(const r of msg.response||[]){if(r.tradeStatus&&((r.tradeStatus.codes||[]).includes('RTJ')||msg.msgid===28)){const v=r.tradeStatus.tradeStatus;this.state.market=v===99?'已闭盘':v===40?'暂停交易':[10,20,27,30].includes(v)?'开盘中':'市场状态待确认'}for(const q of r.quotation||[]){const item=mapQuote(q,this.metadata);if(!item)continue;const sourceKey=item.code+'/'+item.side;const rawStamp=Number(q.quoteTime);const stamp=Number(item.sourceTime)||((Number.isFinite(rawStamp)&&rawStamp>0)?rawStamp:0);if(stamp>0&&stamp<(this.lastSource.get(sourceKey)||0))continue;if(stamp>0)this.lastSource.set(sourceKey,stamp);const row=this.quotes.find(r=>r.code===item.code);const old=row[item.side];const key=`${item.code}/${item.side}`;row[item.side]=item.price;row[item.side+'Current']=true;row[item.side+'Time']=Date.now();row[item.side+'SourceTime']=item.sourceTime;for(const field of ['open','high','low','preClose','updown','updownRate'])if(item[field]!=null)row[item.side+field[0].toUpperCase()+field.slice(1)]=item[field];row.precision=item.precision;row.available=true;
    // Record the first observation of every connection, then actual changes only.
    if(!this.lastPrices.has(key)||old!==item.price){this.lastPrices.set(key,item.price);this.emit('quote',{...item,time:Date.now(),session:this.state.session,id:randomUUID()})}
   }}this.emit('status',this.snapshot());
  }catch{this.publish('error','报价格式发生变化，稍后重连');ws.terminate()}});
  ws.on('error',()=>this.publish('reconnecting','行情连接失败，正在重试'));
  ws.on('close',()=>{clearInterval(timer);if(ws!==this.socket)return;for(const item of this.pending.values()){clearTimeout(item.timer);item.reject(Error('行情连接已中断'))}this.pending.clear();this.quotes.forEach(q=>{q.available=false;q.bidCurrent=false;q.askCurrent=false});if(this.stopped)return;const delay=Math.min(60000,2000*2**Math.min(this.attempt++,5));this.publish('reconnecting',`连接中断，${Math.round(delay/1000)} 秒后重试`);this.retry=setTimeout(()=>this.connect(),delay)});
 }
 reconnect(){if(this.stopped){this.start();return}if(this.socket?.readyState===WebSocket.OPEN||this.socket?.readyState===WebSocket.CONNECTING)this.socket.terminate();else this.connect()}
 async history({code='JZJ_ag',side='ask',period='1',size=300,endTime=0}={}){if(this.state.status!=='connected')throw Error('融通金行情尚未连接');period=String(period);const freq=OFFICIAL_PERIODS[period];if(!freq)throw Error('不支持的 K 线周期');const flag=side==='bid'?'B':'S';const contract=[...this.metadata.values()].find(item=>item.group===code&&item.bsflag===flag);if(!contract)throw Error('所选行情合约信息尚未就绪');const requested=Math.min(1000,Math.max(20,Number(size)||300)),seconds=period.endsWith('s');const queryCondition=seconds?{infoDays:3}:{size:requested};if(Number(endTime)>0)queryCondition.endtime=Math.floor(Number(endTime)/1000);const message=await this.request(20,{codes:[contract.code],freq:[freq],queryCondition});const candles=(seconds?aggregateCandles(mapInformationQuotes(message,contract.code),period):mapHistoricalQuotes(message,contract.code,freq)).slice(-requested);return{source:seconds?'融通金官方逐笔行情派生K线':'融通金官方历史行情',sourceUrl:'https://i.jzj9999.com/quoteh5',contract:contract.code,side,period,frequency:freq,candles}}
 stop(){this.stopped=true;clearTimeout(this.retry);this.socket?.terminate();this.quotes.forEach(q=>{q.available=false;q.bidCurrent=false;q.askCurrent=false});this.publish('stopped','监控已停止')}
}



