const { contextBridge, ipcRenderer } = require('electron');
const invoke = (name, args) => ipcRenderer.invoke(name, args);
const on = (channel, callback) => { const listener = (_event, value) => callback(value); ipcRenderer.on(channel, listener); return () => ipcRenderer.removeListener(channel, listener); };

contextBridge.exposeInMainWorld('monitor', Object.freeze({
  status: () => invoke('status'),
  onStatusChanged: callback => on('status-changed', callback),
  candles: (code, side, interval, size = 300, endTime = 0) => invoke('candles', { code, side, interval, size, endTime }),
  news: (limit = 100) => invoke('news', { limit }),
  reconnect: () => invoke('reconnect'),
  openSource: () => invoke('open-source'),
  openChart: () => invoke('open-chart'),
  openNewsSource: () => invoke('open-news-source'),
  openData: () => invoke('open-data'),
  quit: () => invoke('quit'),
  minimize: () => invoke('window-minimize'),
  maximize: () => invoke('window-maximize'),
  close: () => invoke('window-close'),
  showMain: panel => invoke('show-main', { panel }),
  onNavigatePanel: callback => on('navigate-panel', callback),
  closeMini: () => invoke('close-mini'),
  appSettings: () => invoke('app-settings'),
  displayInfo: () => invoke('display-info'),
  operationLogs: () => invoke('operation-logs'),
  systemLogs: () => invoke('system-logs'),
  logSystemEvent: value => invoke('log-system-event', value),
  logOperation: value => invoke('log-operation', value),
  restoreOperation: id => invoke('restore-operation', { id }),
  saveAppSettings: value => invoke('save-app-settings', value),
  testSound: value => invoke('test-sound', typeof value === 'object' ? value : { repeats: value }),
  audioStatus: () => invoke('audio-status'),
  onAlertSound: callback => on('play-alert-sound', callback),
  onSpeakAlert: callback => on('speak-alert', callback),
  onAppSettingsChanged: callback => on('app-settings-changed', callback),
  mailSettings: () => invoke('mail-settings'),
  saveMailSettings: value => invoke('save-mail-settings', value),
  toggleMail: enabled => invoke('toggle-mail', { enabled }),
  saveRecipient: value => invoke('save-recipient', value),
  toggleRecipient: (id, enabled) => invoke('toggle-recipient', { id, enabled }),
  deleteRecipient: id => invoke('delete-recipient', { id }),
  testMailConnection: value => invoke('test-mail-connection', value),
  sendTestMail: () => invoke('send-test-mail'),
  onMailSettingsChanged: callback => on('mail-settings-changed', callback),
  alerts: () => invoke('alerts'),
  saveAlertRule: value => invoke('save-alert-rule', value),
  toggleAlertRule: (id, enabled) => invoke('toggle-alert-rule', { id, enabled }),
  deleteAlertRule: id => invoke('delete-alert-rule', { id }),
  clearAlertEvents: () => invoke('clear-alert-events'),
  onAlertsChanged: callback => on('alerts-changed', callback),
  aiSettings: () => invoke('ai-settings'),
  onAiSettingsChanged: callback => on('ai-settings-changed', callback),
  onAiProgress: callback => on('ai-analysis-progress', callback),
  saveAiSettings: value => invoke('save-ai-settings', value),
  analyzeAi: code => invoke('analyze-ai', { code }),
  openExternal: url => invoke('open-external', { url }),
}));
